# Generated by Django 5.2.1 on 2025-05-26 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_municipio', models.CharField(max_length=50, unique=True)),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('populacao', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='RegiaoImediata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioma', models.CharField(max_length=30)),
                ('nome_regiao', models.CharField(max_length=50, unique=True)),
                ('clima_regiao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Região Imediata',
                'verbose_name_plural': 'Regiões Imediatas',
            },
        ),
        migrations.CreateModel(
            name='Satelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_satelite', models.CharField(max_length=100)),
                ('pais_origem', models.CharField(max_length=50)),
                ('tipo_orbita', models.CharField(choices=[('LEO', 'Órbita Terrestre Baixa'), ('GEO', 'Órbita Geossíncrona'), ('MEO', 'Órbita Terrestre Média')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FocoQueimada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=9)),
                ('potencia_rad', models.FloatField()),
                ('id_municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queimadas_app.municipio')),
            ],
            options={
                'verbose_name': 'Foco de Queimada',
                'verbose_name_plural': 'Focos de Queimada',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='id_regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queimadas_app.regiaoimediata'),
        ),
        migrations.CreateModel(
            name='SateliteQueimada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_queimada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queimadas_app.focoqueimada')),
                ('id_satelite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queimadas_app.satelite')),
            ],
            options={
                'verbose_name': 'Relação Satélite-Queimada',
                'verbose_name_plural': 'Relações Satélite-Queimada',
            },
        ),
        migrations.AddField(
            model_name='focoqueimada',
            name='satelites',
            field=models.ManyToManyField(through='queimadas_app.SateliteQueimada', to='queimadas_app.satelite'),
        ),
        migrations.AddConstraint(
            model_name='municipio',
            constraint=models.CheckConstraint(condition=models.Q(('area_km2__gt', 0)), name='ck_area_positiva'),
        ),
        migrations.AddConstraint(
            model_name='satelitequeimada',
            constraint=models.UniqueConstraint(fields=('id_queimada', 'id_satelite'), name='pk_ligacao_queimada_satelite'),
        ),
        migrations.AddConstraint(
            model_name='focoqueimada',
            constraint=models.UniqueConstraint(fields=('data_hora', 'latitude', 'longitude'), name='unq_foco_queimada'),
        ),
    ]
